name: Deploy VROOM to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'vroom/**'
      - '.github/workflows/deploy-vroom.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy VROOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy VROOM to Fly.io
        run: flyctl deploy --local-only
        working-directory: vroom
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DOCKER_BUILDKIT: '1'
